### ISSUE TITLE
Faltan varios 4 campos

### ISSUE THREAD

**Issue by jfrchicanog** [jfrchicanog/ewp-reference-connector#11]
https://github.com/jfrchicanog/ewp-reference-connector/blob/5c2636560b344f2fb453c384a15f318a92e612b3/ewp-reference-connector/src/main/java/eu/erasmuswithoutpaper/iia/control/IiaConverter.java#L118

Faltan iia_id, signingContact, signingDate y contact (este último es una lista o colección).

**Comment by Dalia-git** [comment]
-Solo veo esta solucion ya en otra propiedad se asigna el iiCode
converted.setIiaId(iia.getId());
-Iia tiene otras dos propiedades startDate, endDate. No se cual de todas ellas deberia utilizar. 
converted.setSigningDate(ConverterHelper.convertToXmlGregorianCalendar(iia.getModifyDate()));
-La entidad del api 'converted'  espera una instacia mientra que el partner contiene una coleccion de contactos. Asumi tomar el primero. 
converted.setSigningContact(contacts.get(0));

**Comment by Dalia-git** [comment]
Con relacion a SigningContact creo que lo que se debe hacer es crear la nueva propiedad que ahora no existe porque estos valores que en el comentario anterior puse se corresponden mas bien con otro issue

**Comment by Dalia-git** [comment]
Added property

**Comment by jfrchicanog** [comment]
Creo que Star date y end date están obsoletas en esta versión de la api

**Comment by jfrchicanog** [comment]
Correcto, startDate y endDate están obsoletas. Por otro lado, hay que añadir SigningDate, creo que es diferente de ModifDate.

**Comment by Dalia-git** [comment]
Added property
