### ISSUE TITLE
Añadir contactos

### ISSUE THREAD

**Issue by jfrchicanog** [jfrchicanog/ewp-reference-connector#13]
https://github.com/jfrchicanog/ewp-reference-connector/blob/5c2636560b344f2fb453c384a15f318a92e612b3/ewp-reference-connector/src/main/java/eu/erasmuswithoutpaper/iia/control/IiaConverter.java#L156

**Comment by jfrchicanog** [comment]
De los dos socios, sending y receiv8ng. Ver https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/v6.0.1/endpoints/get-response.xsd

**Comment by Dalia-git** [comment]
Invocado el metodo  addToMobilitySpecification(conv , cc); en los metodos addToStaffMobilitySpecification y addToStudentMobilitySpecification

**Comment by Dalia-git** [comment]
Invocado el metodo addToMobilitySpecification(conv , cc); en los metodos addToStaffMobilitySpecification y addToStudentMobilitySpecification
