### ISSUE TITLE
Añadir blended

### ISSUE THREAD

**Issue by jfrchicanog** [jfrchicanog/ewp-reference-connector#19]
https://github.com/jfrchicanog/ewp-reference-connector/blob/5c2636560b344f2fb453c384a15f318a92e612b3/ewp-reference-connector/src/main/java/eu/erasmuswithoutpaper/iia/control/IiaConverter.java#L167

Falta blended.

**Comment by jfrchicanog** [comment]
La especificación de la respuesta está en https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/v6.0.1/endpoints/get-response.xsd

**Comment by jfrchicanog** [comment]
También se puede consultar en Java en las clases delnproyecto EWP-conector-api

**Comment by Dalia-git** [comment]
Added property
