### ISSUE TITLE
Comprobar que el notifier_hei_id está cubierto por la firma

### ISSUE THREAD

**Issue by jfrchicanog** [jfrchicanog/ewp-reference-connector#23]
https://github.com/jfrchicanog/ewp-reference-connector/blob/40fe0f2cb200cf19f7e580358c3a6c411970145b/ewp-reference-connector/src/main/java/eu/erasmuswithoutpaper/iia/boundary/IiaResource.java#L105

Está especificado aquí: https://github.com/erasmus-without-paper/ewp-specs-api-iia-cnr

Hay código en la misma clase que muestra cómo hacerlo (líneas 161 a 165). 

La prioridad de esto es baja (es una cuestión de seguridad)

**Comment by Dalia-git** [comment]
No se que debo hacer en caso que el notifier_hei_id no este contenida en los heis cubiertos por la firma

**Comment by jfrchicanog** [comment]
Si el notifier_heid no está cubierto por el certificado, o la firma, se debe devolver un EwpException explicando el problema (the client signature does not cover the notifier_heid)

**Comment by Dalia-git** [comment]
Se lanza una exception si no esta cubierta por la firma
