### ISSUE TITLE
El UUID del acuerdo no es suficiente

### ISSUE THREAD

**Issue by jfrchicanog** [jfrchicanog/ewp-reference-connector#33]
https://github.com/jfrchicanog/ewp-reference-connector/blob/c9b96961117150fdf0b645fb9726eb643750175e/ewp-reference-connector/src/main/java/eu/erasmuswithoutpaper/iia/approval/boundary/IiaApprovalResource.java#L100

Hace falta indicar también la institución que lo aprueba, aunque (solo pueda ser una) para asegurarse de que todo es correcto. Esto es algo que vienen en los propios parámetros, pero esta implementación no cumple la especificación y por eso no está disponible.

**Comment by Dalia-git** [comment]
Esta es la informacion enviada por Manuel. Hay que modificar la informacion que el solicta con el nuevo campo en el json. 

Para crear una notificación deberás hacer un POST a uno de estos endpoints con la siguiente información en un JSON:

{
    "agreement_uuid": "A81F01BB-F8BC-4EC6-A741-D1D0436047D2",  # El UUID del agreement
    "description": "Algún texto con información adicional del cara al usuario"
}

**Comment by jfrchicanog** [comment]
A Algoria no es necesario que le pases la institución que lo aprueba, esta comprobación se puede mantener en EWP. Lo que hay que hacer es comprobar que el approving_hei_id está cubierto por el certificado de la petición y que coincide con el otro partner del acuerdo. Toda esa información está disponible en EWP. Una vez hecho esto, se guarda en la BD la aprobación del acuerdo y se notifica a Algoria, A Algoria le basta con conocer el UUID del acuerdo aprobado (como el acuerdo es de la UMA ese UUID es único dentro de la UMA y de Algoria).

**Comment by jfrchicanog** [comment]
En definitiva, la implementación que tenías en esa línea era correcta, simplemente no caí en que solo se pueden notificar aprobaciones de acuerdos de la UMA.
