### ISSUE TITLE
Incorrect relative url

### ISSUE THREAD

**Issue by jfrchicanog** [jfrchicanog/ewp-reference-connector#4]
https://github.com/jfrchicanog/ewp-reference-connector/blob/5c2636560b344f2fb453c384a15f318a92e612b3/ewp-reference-connector/src/main/java/eu/erasmuswithoutpaper/factsheet/boundary/FactsheetManifestEntry.java#L26

**Comment by Dalia-git** [comment]
Changed to factsheet.setUrl(baseUri + "factsheet/get");

**Comment by Dalia-git** [comment]
Changed to factsheet.setUrl(baseUri + "factsheet/get");

**Comment by jfrchicanog** [comment]
Propongo que sea "factsheet", no hace falta el get, ya que solo hay un endpoint aquí. También falta @EwpAuthenticate.
