### ISSUE TITLE
Comprobación de hei_id innecesaria

### ISSUE THREAD

**Issue by jfrchicanog** [jfrchicanog/ewp-reference-connector#44]
https://github.com/jfrchicanog/ewp-reference-connector/blob/d92a54a71fb433535027b2b247fe463d5827b51b/ewp-reference-connector/src/main/java/eu/erasmuswithoutpaper/iia/approval/boundary/IiaApprovalResource.java#L163

Aquí no hace falta comprobar el hei_id, porque es nuestra universidad y basta con no almacenar acuerdos que no tengan a nuestra universidad como uno de los socios.

**Comment by Dalia-git** [comment]
Aqui estoy filtrando los acuerdo cuyo receiving_partener sean  hei_id porque el owner_id lo compruebo contra el sending_partner

**Comment by jfrchicanog** [comment]
Lo veo, pero en realidad también podría ser al revés. Es decir, el owner podría ser el receiving_partner y el sending podríamos ser nosotros. En los dos casos hay que devolverlo. Lo normal es que se den los dos en el mismo acuerdo. Pero para ser estrictamente correctos, hay que comprobar que se da lo uno o lo otro.
