### ISSUE TITLE
Reducir duplicidad de código

### ISSUE THREAD

**Issue by jfrchicanog** [jfrchicanog/ewp-reference-connector#46]
Los dos últimos métodos se parecen mucho, debe haber alguna forma de evitar ese código duplicado.

https://github.com/jfrchicanog/ewp-reference-connector/blob/63fd7303749ce04fbc2fd2b144e1978307fea9ff/ewp-reference-connector/src/main/java/eu/erasmuswithoutpaper/iia/boundary/IiaResource.java#L471

**Comment by Dalia-git** [comment]
Hice una refactorizacion extrayendo el codigo comun en un tercer metodo.
