### ISSUE TITLE
The client asks for the hei_id

### ISSUE THREAD

**Issue by jfrchicanog** [jfrchicanog/ewp-reference-connector#5]
https://github.com/jfrchicanog/ewp-reference-connector/blob/5c2636560b344f2fb453c384a15f318a92e612b3/ewp-reference-connector/src/main/java/eu/erasmuswithoutpaper/factsheet/boundary/FactsheetResource.java#L49

**Comment by jfrchicanog** [comment]
@Dalia-git

**Comment by Dalia-git** [comment]
Changed by hei_id
