### ISSUE TITLE
Revisar filtros

### ISSUE THREAD

**Issue by jfrchicanog** [jfrchicanog/ewp-reference-connector#8]
https://github.com/jfrchicanog/ewp-reference-connector/blob/5c2636560b344f2fb453c384a15f318a92e612b3/ewp-reference-connector/src/main/java/eu/erasmuswithoutpaper/iia/boundary/IiaResource.java#L123

Mirar el documento: https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/v6.0.1/endpoints/index.md

Allí se indican varios filtros opcionales que hay que implementar para limitar la búsqueda a ciertos socios, años académicos o fecha de modificación.

**Comment by Dalia-git** [comment]
Estos filtros se corresponden con los parametros que se reciben. En ese metodo solo se recibe el heiId.

**Comment by jfrchicanog** [comment]
Hay que añadir los parámetros faltantes :-)

**Comment by Dalia-git** [comment]
Added new parameters, implemented the corresponding filters depending the received parameters

**Comment by jfrchicanog** [comment]
Reabro este issue, las razones están en los comentarios del commit.

**Comment by jfrchicanog** [comment]
Sigue habiendo un espacio en el modifiedSince, no está corregido.
