### ISSUE TITLE
Añadir iia_code

### ISSUE THREAD

**Issue by jfrchicanog** [jfrchicanog/ewp-reference-connector#9]
https://github.com/jfrchicanog/ewp-reference-connector/blob/5c2636560b344f2fb453c384a15f318a92e612b3/ewp-reference-connector/src/main/java/eu/erasmuswithoutpaper/iia/boundary/IiaResource.java#L74

Pueden llamar a este endpoint (get) con iia_code en lugar de iia_id. Ver la documentación aquí:

https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/v6.0.1/endpoints/get.md

**Comment by jfrchicanog** [comment]
También aquí: https://github.com/jfrchicanog/ewp-reference-connector/blob/5c2636560b344f2fb453c384a15f318a92e612b3/ewp-reference-connector/src/main/java/eu/erasmuswithoutpaper/iia/boundary/IiaResource.java#L81

**Comment by Dalia-git** [comment]
Modified by public javax.ws.rs.core.Response getPost(@FormParam("hei_id") String heiId, @FormParam("iia_id") List<String> iiaIdList, @QueryParam("iia_code") List<String> iiaCodeList) {

**Comment by jfrchicanog** [comment]
Había algunos errores que he corregido, pero sigue sin estar completo. Un iia_code es un identificador diferente al iia_id y, por tanto, no puede buscarse de la misma forma. El método iiaGet solo busca por iia_id, no por iiaCode, por lo que hay que añadir un método para que busque por este último y pasarle la lista de iiaCode (o modificar el método existente par que interprete  la lista como ID o como Code).

**Comment by Dalia-git** [comment]
Modificado el metodo para que se busque por code o id en dependencia de la coleccion que se recibe. Modificado el metodo existente para que interprete la lista segun el parametro que recibe.
